import { Navbar } from '@/app/components/nav/Navbar';
import { NavItem } from '@/app/components/nav/NavItem';
import { ReactQueryProvider } from '@/app/lib/providers';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen `}
      >
        <ReactQueryProvider>
          <div className='h-full flex overflow-auto'>
            <Navbar>
              <Link href='/overview'>
                <NavItem>Overview</NavItem>
              </Link>
              <Link href='/about'>
                <NavItem>About</NavItem>
              </Link>
              <Link href='/countries'>
                <NavItem>Countries</NavItem>
              </Link>
              <Link href='/posts'>
                <NavItem>Posts</NavItem>
              </Link>
            </Navbar>
            <main className=''> {children}</main>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
